YTLitePlus/YTLitePlus

README.md
Source/Settings.xm
Source/VersionSpooferLite.xm

Hello I made a different version of the Version Spoofer Tweak specifically for YTLitePlus. Its a lighter version with lesser options and I also putted info next to the version number so people will know what changes the app.

Added YouTube Version Spoofer (Lite)

---

.github/workflows/update-submodules.yml

Hello Balackburn! I made it easier to update the submodules without needing to use Git! I hope this helps make it easier for you to update submodules. It saves a lot of time

Ability to Update Submodules using Actions

---

Header.h
Source/LowContrastMode.xm

This tweak that is a bit different. I implemented some sort of `label` modifier for the class `_ASDisplayView`. If you don’t like the changes you can close the pull request or contribute if you want to expand upon the tweak. Anyways hoped my past pull requests were unique. I appreciate helping!

LowContrastMode v1.3.1

---

Source/LowContrastMode.xm
Source/Settings.xm
Source/VersionSpooferLite.xm
YTLitePlus.xm

Hello Balackburn! I tried out your latest release and it was really confusing to navigate when there are so many duplicated options so I decided to do a pull request to remove duplicates, fix broken options & improvements! 😎

Improvements & Removed Duplicated Options

---

README.md
Source/LowContrastMode.xm
Source/Settings.xm
YTLitePlus.xm

Here’s this to re-add YTSpeed.
other changes:
- Repositioned the YTLitePlus Section (now it’s next to YTLite Section hopefully)
- Removed `Video Player Options` in YTLitePlus (did change was made because there was only 1 option so moved the following option to `miscellaneous`)

Re-added YTSpeed Tweak

---

Makefile

You forgot the `Resources` without that the localization probably wouldn’t work correctly

Fix YTNoCommunityPosts Bundle

---

.github/workflows/delete-workflow-runs.yml

Hey Balackburn! Here’s this! Use this to delete any of the workflow actions! This can wipe out and make thé `Actions` Tab cleaner.

Added Delete Workflow Runs Action

---

Source/Themes.xm

Themes were improved! Works on the latest version and changes a ton of stuff! The themes were based off of YouTube Reborn v4.0.9

Improved Themes

---

Source/Themes.xm

hello Balackburn! I'm putting this here! I think I successfully Implemented the new and improved OLED & old dark theme options! this took me days and at least a ton of effort to get it to work with the app but glad I was happy to help!

Revamped OLED & Old Dark Themes!

---

Source/Themes.xm

removed something in the code that is based off of the Comment Section. my fault y'all.

Fix comment section

---

.gitmodules

I modified the .gitmodules file and immediately changed the submodule for YTNoCommunityPosts because I could possibly delete my fork so I did this just in case.

Change YTNoCommunityPosts Submodule

---

Source/LowContrastMode.xm

Hey Balackburn! Here’s a new update to LowContrastMode!
the code has been overhauled to have some new methods related to text and has better code organization.
but the problem with LowContrastMode is that it is STILL not compatible with YouTube v17.39.4 or newer
I don’t know what to do to make the tweak compatible with modern versions, and I apologize for that. 😥

LowContrastMode v1.4.0

---

Source/Settings.xm
Source/VersionSpooferLite.xm
YTLitePlus.xm
lang/YTLitePlus.bundle/en.lproj/Localizable.strings
lang/YTLitePlus.bundle/template.lproj/Localizable.strings

I have contributed on this tweak. I added a ton of new options and then removed an option called “Disable WiFi Related Settings” since it was replaced and then updated the Version Spoofer (Lite) and made the localization better for you 👍

Contribution Changes

---

.github/workflows/buildapp.yml

Same like previous
Wiki does need to be updated after merge

Get ytlite ver from project instead of manual input

---

lang/YTLitePlus.bundle/de.lproj/Localizable.strings

I have corrected and adapted this file, which was obviously previously translated with google translate, as far as possible. Several sentences had to be roughly adapted for a better German understanding.

Update Localizable.strings (german)

---

.github/workflows/buildapp.yml

Reverts YTLitePlus/YTLitePlus#164
Noticed that this didn't do anything, this should be configured in the makefile of the projects/tweaks that are used.

Revert "Fix Theo’s warning about not defining build version"

---

Source/Settings.xm
YTLitePlus.xm
lang/YTLitePlus.bundle/ar.lproj/Localizable.strings
lang/YTLitePlus.bundle/de.lproj/Localizable.strings
lang/YTLitePlus.bundle/en.lproj/Localizable.strings
lang/YTLitePlus.bundle/es.lproj/Localizable.strings
lang/YTLitePlus.bundle/fr.lproj/Localizable.strings
lang/YTLitePlus.bundle/ja.lproj/Localizable.strings
lang/YTLitePlus.bundle/pt.lproj/Localizable.strings
lang/YTLitePlus.bundle/ro.lproj/Localizable.strings
lang/YTLitePlus.bundle/ru.lproj/Localizable.strings
lang/YTLitePlus.bundle/template.lproj/Localizable.strings
lang/YTLitePlus.bundle/tr.lproj/Localizable.strings
lang/YTLitePlus.bundle/zh_TW.lproj/Localizable.strings

My code, copied from uYouEnhanced

Add Hide Home Tab

---

.gitmodules
Source/Settings.xm
YTLitePlus.h
YTLitePlus.xm
lang/YTLitePlus.bundle/ar.lproj/Localizable.strings
lang/YTLitePlus.bundle/de.lproj/Localizable.strings
lang/YTLitePlus.bundle/en.lproj/Localizable.strings
lang/YTLitePlus.bundle/es.lproj/Localizable.strings
lang/YTLitePlus.bundle/fr.lproj/Localizable.strings
lang/YTLitePlus.bundle/ja.lproj/Localizable.strings
lang/YTLitePlus.bundle/pt.lproj/Localizable.strings
lang/YTLitePlus.bundle/ro.lproj/Localizable.strings
lang/YTLitePlus.bundle/ru.lproj/Localizable.strings
lang/YTLitePlus.bundle/template.lproj/Localizable.strings
lang/YTLitePlus.bundle/tr.lproj/Localizable.strings
lang/YTLitePlus.bundle/vi.lproj/Localizable.strings
lang/YTLitePlus.bundle/zh_TW.lproj/Localizable.strings

More fun things:
- YTTapToSeek: Single tap anywhere on the player bar to jump there
- Disable Pull-To-Fullscreen gesture in the video player
- Default remaining time/Disable time toggle/Always use remaining time
- Disable ambient mode in either portrait or fullscreen

Misc features

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/feature-request.yaml
.github/ISSUE_TEMPLATE/question.yaml
.github/workflows/delete-workflow-runs.yml

Update and add templates from uYouEnhanced to improve issue tracking

Sync uYouEnhanced Templates

---

.github/workflows/buildapp.yml
.github/workflows/delete-workflow-runs.yml
Makefile

Add job summary when building with actions

---

Source/Settings.xm
YTLitePlus.h
YTLitePlus.xm
lang/YTLitePlus.bundle/ar.lproj/Localizable.strings
lang/YTLitePlus.bundle/de.lproj/Localizable.strings
lang/YTLitePlus.bundle/en.lproj/Localizable.strings
lang/YTLitePlus.bundle/es.lproj/Localizable.strings
lang/YTLitePlus.bundle/fr.lproj/Localizable.strings
lang/YTLitePlus.bundle/ja.lproj/Localizable.strings
lang/YTLitePlus.bundle/pt.lproj/Localizable.strings
lang/YTLitePlus.bundle/ro.lproj/Localizable.strings
lang/YTLitePlus.bundle/ru.lproj/Localizable.strings
lang/YTLitePlus.bundle/template.lproj/Localizable.strings
lang/YTLitePlus.bundle/tr.lproj/Localizable.strings
lang/YTLitePlus.bundle/vi.lproj/Localizable.strings
lang/YTLitePlus.bundle/zh_TW.lproj/Localizable.strings

Copy Hide HUD and Hide Collapse Button

---

Source/Settings.xm
YTLitePlus.xm
lang/YTLitePlus.bundle/ar.lproj/Localizable.strings
lang/YTLitePlus.bundle/de.lproj/Localizable.strings
lang/YTLitePlus.bundle/en.lproj/Localizable.strings
lang/YTLitePlus.bundle/es.lproj/Localizable.strings
lang/YTLitePlus.bundle/fr.lproj/Localizable.strings
lang/YTLitePlus.bundle/ja.lproj/Localizable.strings
lang/YTLitePlus.bundle/pt.lproj/Localizable.strings
lang/YTLitePlus.bundle/ro.lproj/Localizable.strings
lang/YTLitePlus.bundle/ru.lproj/Localizable.strings
lang/YTLitePlus.bundle/template.lproj/Localizable.strings
lang/YTLitePlus.bundle/tr.lproj/Localizable.strings
lang/YTLitePlus.bundle/vi.lproj/Localizable.strings
lang/YTLitePlus.bundle/zh_TW.lproj/Localizable.strings

Remove speed popup

---

YTLitePlus.xm

Fix OLED live chat

---

Source/Settings.xm
YTLitePlus.h
lang/YTLitePlus.bundle/ar.lproj/Localizable.strings
lang/YTLitePlus.bundle/bg.lproj/Localizable.strings
lang/YTLitePlus.bundle/de.lproj/Localizable.strings
lang/YTLitePlus.bundle/en.lproj/Localizable.strings
lang/YTLitePlus.bundle/es.lproj/Localizable.strings
lang/YTLitePlus.bundle/fr.lproj/Localizable.strings
lang/YTLitePlus.bundle/ja.lproj/Localizable.strings
lang/YTLitePlus.bundle/pt.lproj/Localizable.strings
lang/YTLitePlus.bundle/ro.lproj/Localizable.strings
lang/YTLitePlus.bundle/ru.lproj/Localizable.strings
lang/YTLitePlus.bundle/template.lproj/Localizable.strings
lang/YTLitePlus.bundle/tr.lproj/Localizable.strings
lang/YTLitePlus.bundle/vi.lproj/Localizable.strings
lang/YTLitePlus.bundle/zh_TW.lproj/Localizable.strings

Basic Video player

---

Source/Settings.xm
YTLitePlus.h
YTLitePlus.xm

Fix settings crash

---

lang/YTLitePlus.bundle/vi.lproj/Localizable.strings

Update according to template.lproj

Update Vietnamese localization

---

lang/YTLitePlus.bundle/zh_CN.lproj/Localizable.strings

Added Simplified Chinese support

Added Simplified Chinese support

---

lang/YTLitePlus.bundle/ko.lproj/Localizable.strings

Add Korean localization

---

.github/workflows/buildapp.yml

patch SDK_PATH in Makefile when using non-default sdk version
